//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandSterlingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eBedroom_Master
    {
        public string Record_Id { get; set; }
        public string Bedrooms { get; set; }
        public string Bedrooms_BI { get; set; }
    }
}
