//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandSterlingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eCountryCity_Master
    {
        public string Record_Id { get; set; }
        public string Country_Desc { get; set; }
        public string City_Desc { get; set; }
        public string Country_Desc_Ar { get; set; }
        public string City_Desc_Ar { get; set; }
    }
}
