//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandSterlingProject2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ePMS2040Entities3 : DbContext
    {
        public ePMS2040Entities3()
            : base("name=ePMS2040Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country_Master> Country_Master { get; set; }
        public virtual DbSet<eBedroom_Master> eBedroom_Master { get; set; }
        public virtual DbSet<eCountryCity_Master> eCountryCity_Master { get; set; }
        public virtual DbSet<eUnitCategory_Master> eUnitCategory_Master { get; set; }
        public virtual DbSet<tbUnit_Master> tbUnit_Master { get; set; }
        public virtual DbSet<tbTestimonials> tbTestimonials { get; set; }
    }
}
